[metadata]
name = trw-storage-plugin
version = 1.0.15
description = TRW Storage Assignments plugin for InvenTree
author = The Roast Works

[options]
packages =
    trw_storage
    trw_storage.migrations
include_package_data = True
install_requires =

[options.package_data]
trw_storage =
    static/trw_storage/*
    templates/trw_storage/*

[options.entry_points]
inventree_plugins =
    TRWStorage = trw_storage.plugin:TRWStoragePlugin
